In [1]:
import numpy as np

## numpy arrays

In [2]:
myList = [10,20,30]

In [3]:
np.array(myList)

array([10, 20, 30])

In [6]:
type(np.array(myList))

numpy.ndarray

## arange

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
 np.arange(10,20,2)

array([10, 12, 14, 16, 18])

## zeros ones

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [11]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## linspace

In [12]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [13]:
np.linspace(0,30,3)

array([ 0., 15., 30.])

In [14]:
np.linspace(0,20,30)

array([ 0.        ,  0.68965517,  1.37931034,  2.06896552,  2.75862069,
        3.44827586,  4.13793103,  4.82758621,  5.51724138,  6.20689655,
        6.89655172,  7.5862069 ,  8.27586207,  8.96551724,  9.65517241,
       10.34482759, 11.03448276, 11.72413793, 12.4137931 , 13.10344828,
       13.79310345, 14.48275862, 15.17241379, 15.86206897, 16.55172414,
       17.24137931, 17.93103448, 18.62068966, 19.31034483, 20.        ])

## eye

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## random

In [18]:
np.random.randn(4)

array([ 2.02143488,  0.43107171, -1.97635552,  0.48185694])

In [19]:
np.random.randn(8,8)

array([[-0.39472348, -0.43381613, -1.09469825, -1.0998021 , -0.29288771,
        -1.09207359,  1.84270581,  0.98531089],
       [-0.01620246,  1.2128652 , -0.96708353, -0.79300135,  0.87974408,
         2.04328037, -0.92629223, -1.56995753],
       [-0.91182024, -0.8898934 ,  0.03081465,  0.1274633 ,  1.36333865,
        -0.07664486, -1.09610102,  0.16545711],
       [-0.12030592,  0.85944453,  3.46431474, -2.26714164, -1.46164643,
        -1.23034814,  1.4627438 , -2.04918036],
       [ 0.05300387,  0.85067283, -0.44806189, -0.93939467,  2.00889286,
         0.48715563, -2.33420131,  0.63833418],
       [ 0.22523477, -0.54763028, -0.77557384,  0.00942788, -0.48253253,
         0.48008829, -0.0672031 , -0.91148072],
       [-0.3957325 ,  0.08211854,  0.67904515,  0.53911002, -0.52165556,
        -1.61408492, -1.05397632,  0.93128476],
       [ 0.82768948, -1.70971312,  0.46371771, -0.88016759, -1.08520911,
        -1.76091931, -0.26749114,  1.05979073]])

In [21]:
np.random.randint(1,20)

12

In [22]:
np.random.randint(1,20,5)

array([18,  4, 17, 14,  4])

## numpy array methods

In [28]:
myNumpyArray = np.arange(0,30)

In [29]:
myNumpyArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [30]:
myNumpyRandomArray = np.random.randint(1,100,20)

In [31]:
myNumpyRandomArray

array([16, 12, 81, 83, 11, 64, 26,  9, 53, 87,  2, 45, 13, 28, 80,  1, 86,
       76, 55, 40])

In [33]:
myNumpyArray.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [34]:
myNumpyArray.max()

29

In [35]:
myNumpyRandomArray.max()

87

In [36]:
myNumpyRandomArray.min()

1

In [37]:
myNumpyRandomArray.argmax()

9

In [38]:
myNumpyRandomArray.argmin()

15

In [39]:
myNumpyArray.shape

(30,)