In [2]:
import numpy as np

In [3]:
myArray = np.arange(0,15)

In [4]:
myArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
myArray[5]

5

In [7]:
myArray[3:5]

array([3, 4])

In [8]:
myArray[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
myArray[2:8]=-5

In [10]:
myArray

array([ 0,  1, -5, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [11]:
otherArray=np.arange(0,24)

In [12]:
otherArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [13]:
otherArray[0:5]

array([0, 1, 2, 3, 4])

In [19]:
slicingArray = otherArray[5:9]

In [23]:
slicingArray[:]=700

In [22]:
slicingArray

array([700, 700, 700, 700])

In [24]:
otherArray

array([  0,   1,   2,   3,   4, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [28]:
theOtherArray = otherArray.copy()

In [32]:
theOtherSlicingArray = theOtherArray[9:15]

In [33]:
theOtherSlicingArray

array([ 9, 10, 11, 12, 13, 14])

In [36]:
theOtherSlicingArray[:]=800

In [37]:
theOtherSlicingArray

array([800, 800, 800, 800, 800, 800])

In [35]:
otherArray

array([  0,   1,   2,   3,   4, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

## matrix 

In [38]:
myList = [[1,2,3],[4,5,6],[7,8,9]]

In [39]:
myMatrix = np.array(myList)

In [40]:
myMatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
myMatrix[0][2]

3

In [43]:
myMatrix[0,2]

3

In [44]:
myMatrix[1:,2]

array([6, 9])

In [45]:
myMatrix[0:,2]

array([3, 6, 9])

In [46]:
myMatrix[1:,1:]

array([[5, 6],
       [8, 9]])

In [47]:
myNewList = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [48]:
myNewList

[[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24]]

In [49]:
myNewMatrix = np.array(myNewList)

In [50]:
myNewMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
myNewMatrix[[0,2,4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

## operations

In [56]:
newArray = np.random.randint(5,100,20)

In [57]:
newArray

array([46, 19, 53, 49, 73, 93, 71, 79, 33, 48,  9, 78, 90, 72, 85, 60,  7,
       78, 96, 77])

In [58]:
newArray>12

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
        True,  True])

In [66]:
 aNewArray = newArray>40

In [67]:
aNewArray

array([ True, False,  True,  True,  True,  True,  True,  True, False,
        True, False,  True,  True,  True,  True,  True, False,  True,
        True,  True])

In [68]:
newArray[aNewArray]

array([46, 53, 49, 73, 93, 71, 79, 48, 78, 90, 72, 85, 60, 78, 96, 77])

In [69]:
newArray.size

20

In [71]:
newArray[newArray<35]

array([19, 33,  9,  7])

In [72]:
lastArray = np.arange(0,24)

In [73]:
lastArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [74]:
lastArray+lastArray

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [76]:
lastArray*lastArray

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [77]:
lastArray-lastArray

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])